name: Release docker image
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease"
        required: true

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      docker_image_version: ${{ steps.get_docker_image_version.outputs.version }}
    steps:
    - name: Get docker image version
      uses: luoqiz/docker-images-latest-version@master
      id: get_docker_image_version
      with:
        image: skewll/docker-image-timetrex
                

  build:
    needs: check_version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
 

      - name: cat docker image version
        run: |
          echo ${{ needs.check_version.outputs.docker_image_version }}


          echo "NEW_VERSION=0.1.0" >> $GITHUB_ENV
  
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: version-tag
        id: tag
        uses: anothrNick/github-tag-action@master # if we use 1 there is a too-be-fixed bug https://github.com/anothrNick/github-tag-action/actions/runs/3139501775/jobs/5099976842#step:1:35 as alternative we could use v1
        env:
          VERBOSE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_API_TAGGING: false # uses git cl
      # auto releases is not working atm and is deleting releases due branch tags
      - name: automatic-draft-release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          draft: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ steps.tag.outputs.tag }}: [title-edit-me] by:${{ github.actor }}"
          automatic_release_tag: ${{ steps.tag.outputs.new_tag }}

      - name: version-tag-major
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          tagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+$"
          tag="$(git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)' | grep -E "$tagFmt" | head -n 1)"
          [[ "$tag" =~ ^([0-9]+) ]] # use ^(v[0-9]+) for vX
          major=${BASH_REMATCH[1]}
          # update major tag
          git tag -f "$major"
          git push -f origin "$major"
          # add vX as 1 is linked to short sha bug https://github.com/anothrNick/github-tag-action/actions/runs/3139501775/jobs/5099976842#step:1:35
          git tag -f "v$major"
          git push -f origin "v$major"
      - name: Update changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release
