name: Release docker image
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease"
        required: true

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      docker_image_version: ${{ steps.get_docker_image_version.outputs.version }}
    steps:
    - name: Get docker image version
      uses: luoqiz/docker-images-latest-version@master
      id: get_docker_image_version
      with:
        image: skewll/docker-image-timetrex
                

  build:
    needs: check_version
    runs-on: ubuntu-latest
    steps:
 

      - name: cat docker image version
        run: |
          echo ${{ needs.check_version.outputs.docker_image_version }}

          myVar=${{ needs.check_version.outputs.docker_image_version }}

          if [[-z "$myVar"]]; then
              echo "myVar is empty"
              echo "NEW_VERSION=0.0.0" >> $GITHUB_ENV
          else
              echo "myVar is not empty"
              echo "NEW_VERSION=${{ needs.check_version.outputs.docker_image_version }}" >> $GITHUB_ENV
          fi
          

      - name: Update changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release

      - name: Commit CHANGELOG.md changes and create tag
        run: |
          git add "CHANGELOG.md"
          git commit -m "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin && git push --tags

      - id: get-changelog
        name: Get version changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: read

      - name: Update GitHub release documentation
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          body: ${{ steps.get-changelog.outputs.changelog }}
          prerelease: ${{ startsWith(github.event.inputs.release-type, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
